# Generated by Django 2.1.7 on 2019-04-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificateDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(blank=True, db_column='Application', max_length=255, null=True)),
                ('startdate', models.DateField(null=True)),
                ('expiredate', models.DateField(null=True)),
                ('environment_type', models.PositiveSmallIntegerField(choices=[(1, 'Dev'), (2, 'QA'), (3, 'UAT'), (4, 'Production')])),
            ],
        ),
        migrations.CreateModel(
            name='servic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(blank=True, db_column='Application', max_length=255, null=True)),
                ('startdate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='serviceDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(blank=True, db_column='Application', max_length=255, null=True)),
                ('startdate', models.DateField(null=True)),
                ('expiredate', models.DateField(null=True)),
                ('environment_type', models.PositiveSmallIntegerField(choices=[(1, 'Dev'), (2, 'QA'), (3, 'UAT'), (4, 'Production')])),
            ],
        ),
    ]
