# Generated by Django 2.1.7 on 2019-04-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedApps_Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatedb',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='CSR/'),
        ),
    ]
